language: generic
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: kl-personal-site
    region: us-east-1
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
